
DROP DATABASE IF EXISTS BDCONCEPTOSINFORMATICOS;

CREATE DATABASE BDCONCEPTOSINFORMATICOS DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

USE BDCONCEPTOSINFORMATICOS;

CREATE TABLE `100IMAGENES` (
	100idimagen MEDIUMINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	100nomficheroimagen CHAR( 50 ) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `200CONCEPTOS` (
	200idconcepto SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	200nomconcepto CHAR( 50 ) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `300USUARIOS` (
	300idusuario SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	300nomusuario CHAR( 20 ) NOT NULL,
	300emailusuario CHAR( 50 ) NOT NULL,
	300contrasennausuario CHAR( 20 ) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `110IMAGENESCONCEPTO` (
    100idimagen MEDIUMINT UNSIGNED, 
    200idconcepto SMALLINT UNSIGNED, 
    PRIMARY KEY ( 100idimagen, 200idconcepto ),
    CONSTRAINT `fk_ IMAGENESCONCEPTO_idimagen` FOREIGN KEY ( 100idimagen ) REFERENCES `100IMAGENES` ( 100idimagen ),
	CONSTRAINT `fk_ IMAGENESCONCEPTO_idconcepto` FOREIGN KEY ( 200idconcepto ) REFERENCES `200CONCEPTOS` ( 200idconcepto )
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `210RELACIONES` (
    200idconcepto1 SMALLINT UNSIGNED, 
    200idconcepto2 SMALLINT UNSIGNED, 
    PRIMARY KEY ( 200idconcepto1, 200idconcepto2 ),
    CONSTRAINT `fk_ RELACIONES_idconcepto1` FOREIGN KEY ( 200idconcepto1 ) REFERENCES `200CONCEPTOS` ( 200idconcepto ),
	CONSTRAINT `fk_ RELACIONES_idconcepto2` FOREIGN KEY ( 200idconcepto2 ) REFERENCES `200CONCEPTOS` ( 200idconcepto )
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `220EXPLICACIONES` (
    220idexplicacion MEDIUMINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
    220textoexplicacion TEXT NOT NULL, 
    200idconcepto SMALLINT UNSIGNED,
    CONSTRAINT `fk_ EXPLICACIONES_idconcepto` FOREIGN KEY ( 200idconcepto ) REFERENCES `200CONCEPTOS` ( 200idconcepto )
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `230ENLACES` (
    230idenlace MEDIUMINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
    230nomenlace CHAR( 80 ) NOT NULL, 
    200idconcepto SMALLINT UNSIGNED,
    CONSTRAINT `fk_ ENLACES_idconcepto` FOREIGN KEY ( 200idconcepto ) REFERENCES `200CONCEPTOS` ( 200idconcepto )
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `310EXPLICACIONESUSUARIOS` (
    220idexplicacion MEDIUMINT UNSIGNED,
    300idusuario SMALLINT UNSIGNED, 
    310numveces TINYINT UNSIGNED,
    PRIMARY KEY ( 220idexplicacion, 300idusuario, 310numveces ),
    CONSTRAINT `fk_ EXPLICACIONESUSUARIOS_idexplicacion` FOREIGN KEY ( 220idexplicacion ) REFERENCES `220EXPLICACIONES` ( 220idexplicacion ),
    CONSTRAINT `fk_ EXPLICACIONESUSUARIOS_idusuario` FOREIGN KEY ( 300idusuario ) REFERENCES `300USUARIOS` ( 300idusuario )
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
