
DROP DATABASE IF EXISTS BDCOCHES;

CREATE DATABASE BDCOCHES DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

USE BDCOCHES;

CREATE TABLE `CONTINENTES` (
     idcontinente TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	 nomcontinente CHAR ( 20 ) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `PAISES` (
     idpais CHAR( 3 ) PRIMARY KEY,
	 nompais CHAR ( 40 ) NOT NULL,
	 idcontinente TINYINT UNSIGNED NOT NULL,
	 CONSTRAINT `fk_PAISES_idcontinente` FOREIGN KEY ( idcontinente ) REFERENCES CONTINENTES ( idcontinente )
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `MARCAS` (
     idmarca TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	 nommarca CHAR ( 30 ) NOT NULL,
	 idpais CHAR( 3 ) NOT NULL,
	 CONSTRAINT `fk_MARCAS_idpais` FOREIGN KEY ( idpais ) REFERENCES PAISES ( idpais )
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `MODELOS` (
     idmodelo SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	 nommodelo CHAR ( 40 ) NOT NULL,
	 aniosalida CHAR( 4 ) NOT NULL,
	 color CHAR ( 30 ) NOT NULL,
	 idmarca TINYINT UNSIGNED NOT NULL,
	 CONSTRAINT `fk_MODELOS_idmarca` FOREIGN KEY ( idmarca ) REFERENCES MARCAS ( idmarca )
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `MODELOSVENDIDOS` (
	 idmodelo SMALLINT UNSIGNED,
	 idpais CHAR( 3 ),
	 PRIMARY KEY ( idmodelo, idpais ),
	 CONSTRAINT `fk_MODELOSVENDIDOS_idmodelo` FOREIGN KEY ( idmodelo ) REFERENCES MODELOS ( idmodelo ),
	 CONSTRAINT `fk_MODELOSVENDIDOS_idpais` FOREIGN KEY ( idpais ) REFERENCES PAISES ( idpais ),
	 importe FLOAT( 8, 2 ) UNSIGNED NOT NULL COMMENT "No más de 1M",
	 fecventa DATE NOT NULL,
	 btipopago BOOLEAN NOT NULL,
	 colorventa CHAR ( 30 ) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
