
DROP DATABASE IF EXISTS BDUF2177GRUPOA;

CREATE DATABASE BDUF2177GRUPOA DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

USE BDUF2177GRUPOA;


CREATE TABLE `400_IMAGENES` (
	400_idimagen MEDIUMINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	400_nomfichero CHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `200_PARADIGMAS` (
	200_idparadigma TINYINT UNSIGNED PRIMARY KEY,
	200_nomparadigma CHAR(30) NOT NULL UNIQUE,
	200_descripcion TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `300_AUTORES` (
	300_idautor SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	300_nomautor CHAR(50) NOT NULL UNIQUE,
	300_fecnacimiento DATE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `100_LENGUAJES` (
	100_idlenguaje SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	100_nomlenguaje CHAR(30) NOT NULL UNIQUE,
	100_aniocreacion CHAR(4) NOT NULL,
	100_weboficial CHAR(100) NULL,
	100_activo BOOLEAN NOT NULL,
	400_idimagen MEDIUMINT UNSIGNED NOT NULL,
	CONSTRAINT `FK100_400_idimagen` FOREIGN KEY ( 400_idimagen ) REFERENCES 400_IMAGENES ( 400_idimagen )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `130_INFLUENCIAS` (
	100_idlenguaje SMALLINT UNSIGNED,
	100_idlenguajeinf SMALLINT UNSIGNED,
	PRIMARY KEY ( 100_idlenguaje, 100_idlenguajeinf ),
	CONSTRAINT `FK130_100_idlenguaje` FOREIGN KEY ( 100_idlenguaje ) REFERENCES 100_LENGUAJES ( 100_idlenguaje ),
	CONSTRAINT `FK130_100_idlenguajeinf` FOREIGN KEY ( 100_idlenguajeinf ) REFERENCES 100_LENGUAJES ( 100_idlenguaje )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `110_LENGUAJESPARADIGMAS` (
	100_idlenguaje SMALLINT UNSIGNED,
	200_idparadigma TINYINT UNSIGNED,
	PRIMARY KEY ( 100_idlenguaje, 200_idparadigma ),
	110_iorden TINYINT UNSIGNED NOT NULL,
	CONSTRAINT `FK110_100_idlenguaje` FOREIGN KEY ( 100_idlenguaje ) REFERENCES 100_LENGUAJES ( 100_idlenguaje ),
	CONSTRAINT `FK110_200_idparadigma` FOREIGN KEY ( 200_idparadigma ) REFERENCES 200_PARADIGMAS ( 200_idparadigma )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `120_LENGUAJESAUTORES` (
	100_idlenguaje SMALLINT UNSIGNED,
	300_idautor SMALLINT UNSIGNED,
	PRIMARY KEY ( 100_idlenguaje, 300_idautor ),
	120_iorden TINYINT UNSIGNED NOT NULL,
	CONSTRAINT `FK120_100_idlenguaje` FOREIGN KEY ( 100_idlenguaje ) REFERENCES 100_LENGUAJES ( 100_idlenguaje ),
	CONSTRAINT `FK120_300_idautor` FOREIGN KEY ( 300_idautor ) REFERENCES 300_AUTORES ( 300_idautor )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;