
DROP DATABASE IF EXISTS BDVIAJES;

CREATE DATABASE BDVIAJES DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

USE BDVIAJES;

-- 1 --

CREATE TABLE `300_PAISES` (
	300_idpais CHAR( 3 ) PRIMARY KEY,
	300_nompais CHAR( 100 ) NOT NULL,
	UNIQUE( 300_nompais )
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- 2 --

CREATE TABLE `200_CIUDADES` (
	200_idciudad SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	200_nomciudad CHAR( 100 ) NOT NULL,
	300_idpais CHAR( 3 ) NOT NULL,
	CONSTRAINT `fk_CIUDADES_idpais` FOREIGN KEY ( 300_idpais ) REFERENCES `300_PAISES` ( 300_idpais )
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `500_MONEDAS` (
	500_idmoneda TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	500_nommoneda CHAR( 100 ) NOT NULL,
	300_idpais CHAR( 3 ) NOT NULL,
	CONSTRAINT `fk_MONEDAS_idpais` FOREIGN KEY ( 300_idpais ) REFERENCES `300_PAISES` ( 300_idpais ),
	UNIQUE( 500_nommoneda )
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- 3 --

CREATE TABLE `250_AEROPUERTOS` (
	250_idaeropuerto SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	250_nomaeropuerto CHAR( 100 ) NOT NULL,
	200_idciudad SMALLINT UNSIGNED NOT NULL,
	CONSTRAINT `fk_AEROPUERTOS_idciudad` FOREIGN KEY ( 200_idciudad ) REFERENCES `200_CIUDADES` ( 200_idciudad ),
	UNIQUE( 250_nomaeropuerto )
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `400_PASAJEROS` (
	400_numpasaporte CHAR( 12 ) PRIMARY KEY,
	400_nombre CHAR( 50 ) NOT NULL,
	400_apellidos CHAR( 50 ) NOT NULL,
	400_fecnacimiento DATE NOT NULL,
	400_direccion CHAR( 200 ) NOT NULL,
	200_idciudad SMALLINT UNSIGNED NOT NULL,
	CONSTRAINT `fk_PASAJEROS_idciudad` FOREIGN KEY ( 200_idciudad ) REFERENCES `200_CIUDADES` ( 200_idciudad )
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- 4 --

CREATE TABLE `100_VUELOS` (
	100_idvuelo INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	250_idaeropuertoorigen SMALLINT UNSIGNED NOT NULL,
	CONSTRAINT `fk_VUELOS_idaeropuertoorigen` FOREIGN KEY ( 250_idaeropuertoorigen ) REFERENCES `250_AEROPUERTOS` ( 250_idaeropuerto ),
	250_idaeropuertodestino SMALLINT UNSIGNED NOT NULL,
	CONSTRAINT `fk_VUELOS_idaeropuertodestino` FOREIGN KEY ( 250_idaeropuertodestino ) REFERENCES `250_AEROPUERTOS` ( 250_idaeropuerto ),
	100_fechorasalida DATETIME NOT NULL,
	100_fechoraprevistallegada DATETIME NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- 5 --

CREATE TABLE `110_RESERVAS` (
	100_idvuelo INT UNSIGNED,
	400_numpasaporte CHAR( 12 ),
	PRIMARY KEY ( 100_idvuelo, 400_numpasaporte ),
	110_fecreserva DATE NOT NULL,
	110_importe FLOAT( 12, 2 ) UNSIGNED NOT NULL,
	500_idmoneda TINYINT UNSIGNED NOT NULL,
	CONSTRAINT `fk_RESERVAS_idvuelo` FOREIGN KEY ( 100_idvuelo ) REFERENCES `100_VUELOS` ( 100_idvuelo ),
	CONSTRAINT `fk_RESERVAS_numpasaporte` FOREIGN KEY ( 400_numpasaporte ) REFERENCES `400_PASAJEROS` ( 400_numpasaporte ),
	CONSTRAINT `fk_RESERVAS_idmoneda` FOREIGN KEY ( 500_idmoneda ) REFERENCES `500_MONEDAS` ( 500_idmoneda)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
	
